pub mod acp;
pub mod chat_channel;
pub mod conversations;
pub mod folder_commands;
pub mod folders;
pub mod mcp;
pub mod project_boot;
pub mod system_settings;
pub mod terminal;
pub mod version_control;
#[cfg(feature = "tauri-runtime")]
pub mod notification;
#[cfg(feature = "tauri-runtime")]
pub mod windows;
