mod error;
pub mod acp;
pub mod chat_channel;
pub mod conversations;
pub mod files;
pub mod folder_commands;
pub mod folders;
pub mod git;
pub mod mcp;
pub mod project_boot;
pub mod system_settings;
pub mod terminal;
pub mod version_control;
pub mod web_server;
